input_features:
    -
        name: dată debut simptome declarate
        type: binary
    -
        name: simptome declarate
        type: numerical
    -
        name: dată internare
        type: binary
    -
        name: simptome raportate la internare
        type: numerical
    -
        name: diagnostic și semne de internare
        type: numerical
    -
        name: istoric de călătorie
        type: binary
    -
        name: mijloace de transport folosite
        type: binary
    -
        name: confirmare contact cu o persoană infectată
        type: binary

output_features:
    -
        name: rezultat testare
        type: binary

training:
    epochs: 10
